In [1]:
from sklearn.datasets import fetch_mldata
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split
import pandas as pd

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


## Download and Load the Data

In [4]:
mnist = fetch_mldata('MNIST original')

In [5]:
mnist

{'DESCR': 'mldata.org dataset: mnist-original',
 'COL_NAMES': ['label', 'data'],
 'target': array([0., 0., 0., ..., 9., 9., 9.]),
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)}

In [6]:
#This are the images
mnist.data.shape

(70000, 784)

In [7]:
#Labels
mnist.target.shape

(70000,)

## Spliting data into training and test sets

In [8]:
train_img, test_img, train_label, test_label = train_test_split(mnist.data, mnist.target, test_size = 1/7.0, random_state = 0)

In [9]:
train_img.shape

(60000, 784)

## Standardizing the data

Since PCA yields a feature subspace that maximizes the variance along the axis, it makes sense to standardize the data, especially, if it is measured on different scales. Standardization of a data set is a common requirement for many machine learning estimators: they might behave badly if the individual features do not more or less look like normally distributed data

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

#Fit on training set only
scaler.fit(train_img)

#Apply transform to both the training set and the test set
train_img = scaler.transform(train_img)
test_img = scaler.transform(test_img)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


## PCA to Speed up Machine Learning Alg(Logistic Regression)

Step 0: Import and use PCA

In [11]:
from sklearn.decomposition import PCA

In [33]:
pca = PCA(n_components = 3)

Fit PCA on training set: !! Train PCA on training set only

In [34]:
pca.fit(train_img)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [35]:
pca.n_components_

3

Apply the mapping (transform) to both the training set and the test set

In [36]:
train_img = pca.transform(train_img)
test_img = pca.transform(test_img)

Step 1: Import the model you want to use

In [20]:
from sklearn.linear_model import LogisticRegression

Step 2: Make an instance of the model

In [21]:
logisticRegr = LogisticRegression(solver = 'lbfgs')

Step 3: Training the model on the data, storing the information learned from the data
Model is learning the relationship between x (digits) and y (labels)

In [22]:
logisticRegr.fit(train_img, train_label)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False)

Step 4: Predict the labels of the new data (new images)
Uses the info the model learned during the model training process

In [23]:
logisticRegr.predict(test_img[0].reshape(1, -1))

array([1.])

In [25]:
logisticRegr.predict(test_img[0:10])

array([1., 9., 2., 2., 7., 1., 8., 3., 3., 7.])

## Measuring model performance

In [26]:
score = logisticRegr.score(test_img, test_label)

In [27]:
score

0.92

In [37]:
pca.explained_variance_ratio_

array([0.05978943, 0.04280363, 0.03958091])

In [38]:
len(pca.explained_variance_ratio_)

3

In [39]:
sum(pca.explained_variance_ratio_)

0.14217396748545924

Link: https://towardsdatascience.com/pca-using-python-scikit-learn-e653f8989e60